### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by willek** [martinjack/telegram-logger-errors#1]
Hello, why is there a check on TLESender.php about string length,
```
if (strlen($this->message) > 263) {
 throw new StringsErrors('Message max length. Max 263 length');
}
```
since we can configure the max length  on config.tle.limit_error_message

it caused an error when the length is over 263,
can we just remove it or something?

**Comment by martinjack** [comment]
Hello.Yes, better to remove

**Comment by willek** [comment]
please update the packagist
