### ISSUE TITLE
Unable to install from composer

### ISSUE THREAD

**Issue by asyou99** [martinjack/telegram-logger-errors#6]
[RuntimeException]                                                                                                                          
  Could not load package ezsystems/ezplatform in http://repo.packagist.org: [UnexpectedValueException] Could not parse version constraint de  
  v-load-varnish-only-when-used as ^2.0@dev: Invalid version string "^2.0@dev"
  [UnexpectedValueException]                                                                                         
  Could not parse version constraint dev-load-varnish-only-when-used as ^2.0@dev: Invalid version string "^2.0@dev"

**Comment by martinjack** [comment]
Добрый день. Версия Laravel какая ?

**Comment by asyou99** [comment]
7.27 php-7.4
пробовал на других пакетах все ок. в гугле встречаются сообщение что это композер виноват но вроде со всеми остальными все нормально.

**Comment by martinjack** [comment]
Ок, я проверю

**Comment by martinjack** [comment]
Laravel 7.27 -7.28 
Всё, работает стабильно. 
Если, что пишите https://t.me/martinjack, помогу
