### ISSUE TITLE
Delete log after exception

### ISSUE THREAD

**Issue by amarkhai** [martinjack/telegram-logger-errors#8]
Hi and thanks for package!
Currently I have a problem with logs which stay in ./storage/app/ folder after unsuccessful sendings. Today I found tons of logs there :-D
Maybe it's better to remove log files even if we get an error during sending to Telegram? 
[Here](https://github.com/martinjack/telegram-logger-errors/blob/master/src/TLESender.php#L390) in catch the block

**Comment by martinjack** [comment]
Added new version 1.7
